import os
from datetime import datetime

from app.core.logger import log
from app.core.config import SUMMARY_TXT_FOLDER


def fmt(d):
    """Format date as MM-DD-YYYY or 'UNKNOWN'."""
    if not d:
        return "UNKNOWN"
    return datetime.strftime(d, "%m-%d-%Y")


def write_summary_files(summary_data):
    """
    Writes PSD-style text summaries.
    """

    for member_key, info in summary_data.items():

        rate = info.get("rate", "UNK")
        last = info.get("last", "UNK")
        first = info.get("first", "")

        # Determine documented period (min start, max end)
        rp = info.get("reporting_periods", [])
        if rp:
            min_s = min(r["start"] for r in rp if r["start"])
            max_e = max(r["end"] for r in rp if r["end"])
        else:
            min_s = None
            max_e = None

        # Valid periods
        valid_periods = info.get("periods", [])

        # Invalid entries
        invalid_unknown = info.get("skipped_unknown", [])
        invalid_dupe = info.get("skipped_dupe", [])

        out = []

        out.append("PSD SEA PAY SUMMARY\n")
        out.append(f"Member: {rate} {last}\n")
        out.append(f"Documented Period: {fmt(min_s)} to {fmt(max_e)}\n")

        # VALID SEA PAY PERIODS
        out.append("\nVALID SEA PAY PERIODS (PAY AUTHORIZED):")

        total_valid_days = 0

        for p in valid_periods:
            ship = p["ship"]
            s = p["start"]
            e = p["end"]
            days = (e - s).days + 1
            total_valid_days += days

            suffix = "s" if days != 1 else ""
            out.append(
                f"\n- {ship} | {fmt(s)} TO {fmt(e)} | {days} Day{suffix}"
            )

        out.append(f"\n\nTotal Valid Days: {total_valid_days}\n")

        # INVALID ENTRIES
        out.append("\nINVALID / NON-PAYABLE ENTRIES:")

        invalid_items = []

        # Unknown or suppressed rows (from SBTT/MITE logic)
        for u in invalid_unknown:
            invalid_items.append((
                u.get("date", ""),
                u.get("ship", "UNK"),
                u.get("reason", "Invalid event")
            ))

        # Duplicate rows
        for d in invalid_dupe:
            invalid_items.append((
                d.get("date", ""),
                d.get("ship", "UNK"),
                d.get("reason", "Duplicate entry for date")
            ))

        # NEW SORT: date first, then ship/event-type
        invalid_items.sort(key=lambda x: (x[0], x[1]))

        unique_invalid_days = set()

        for date, ship, reason in invalid_items:
            out.append(f"\n- {ship} | {date} | {reason}")
            unique_invalid_days.add(date)

        out.append(f"\n\nTotal Invalid Days: {len(unique_invalid_days)}\n")

        # DOCUMENTS PROVIDED
        out.append("\nDOCUMENTS PROVIDED:")
        out.append("\n- Generated Sea Pay PG13")
        out.append("\n- TORIS Sea Pay Cert Sheet")
        out.append("\n- Summary PDF\n")

        # NOTES FOR PSD
        notes = []

        if len(valid_periods) > 1:
            notes.append("Valid events confirmed using continuous-date logic.")

        if len(unique_invalid_days) > 0:
            notes.append("Non-platform, SBTT/MITE, and invalid rows removed per policy.")
            notes.append("TORIS sheet corrected and annotated.")

        if notes:
            out.append("\nNOTES FOR PSD:")
            for n in notes:
                out.append(f"\n- {n}")
            out.append("\n")

        out.append("\nGenerated by STG1 NIVERA – ATGSD SEA PAY PROCESSOR\n")

        # Save Summary TXT
        filename = f"{rate}_{last}_{first}_SUMMARY.txt".replace(" ", "_")
        summary_path = os.path.join(SUMMARY_TXT_FOLDER, filename)

        with open(summary_path, "w", encoding="utf-8") as f:
            f.write("".join(out))

        log(f"SUMMARY WRITTEN → {summary_path}")
